### ISSUE TITLE
Freezes on window builds on chrome.

### ISSUE THREAD

**Issue by divine-sean** [WebOsu-2/webosu-2.github.io#10]
**Describe the bug**
Every beatmap freezes at starting frame on windows chrome.

**To Reproduce**
1. Go to any beatmap on windows, chrome.
2. It freezes.

**Expected behavior**
Game works.

**Screenshots**
![image](https://github.com/WebOsu-2/webosu-2.github.io/assets/174436909/002738f6-ee92-4ed3-a494-f81367567bb1)
![image](https://github.com/WebOsu-2/webosu-2.github.io/assets/174436909/c4e201f9-a7a8-4f5e-b1d5-25b1f11cc89c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version Version 126.0.6478.127

**Comment by Mostlime12195** [comment]
Please attempt to load a beatmap on more popular beatmap, such as Megalovania. If that doesn't work, try the same thing on other browsers.

I cannot seem to be able to reproduce the issue on any browser, nor any device. I also cannot locate the mentioned beatmap.

**Comment by Mostlime12195** [comment]
Closed because I cannot reproduce this issue.
