### ISSUE TITLE
Beatmap problem

### ISSUE THREAD

**Issue by Narumiiro** [WebOsu-2/webosu-2.github.io#13]
When you click a beatmap the music preview will play but you cant play.

**Comment by GuythatUhmCreatesRandomStuff** [comment]
You gotta select a difficulty, you need to click on it several times before it works tho.

**Comment by Mostlime12195** [comment]
No and no. When you click on a beatmap, it starts downloading. You'll see the progress bar at the top left corner of the screen. After the progress bar is complete and turns blue, then you can click on a difficulty and start playing.

P.S. please use the template next time, it really helps.
