### ISSUE TITLE
Maps not downloading

### ISSUE THREAD

**Issue by Emp1r1c** [WebOsu-2/webosu-2.github.io#15]
It shows all of the beat maps and says everything has loaded on the top left but when I click on it, it does not download
I am not sure what is making this happen I have tried almost everything and it does not seem to work (I am on a school laptop) and I kinda want it fixed since its like the only fun game I know that I can play

**Comment by Mostlime12195** [comment]
Thank you so much for typing an issue down for me. When you click on a beatmap, will a dropdown list show up? I'm assuming, from your wording, that it does nothing. I'd also like you to check if anything changes in the top-left box when you click a beatmap?

**Comment by Mostlime12195** [comment]
Hi, I made several changes, please try downloading another beatmap to see if the issue persists.

**Comment by Emp1r1c** [comment]
I think it might be sayobot since the past two webosu sites that used it the same issue happens if that's the case see if you can down load the beat maps and import into mino

**Comment by Mostlime12195** [comment]
Hi, I'd love to put sayobot beatmaps into mino, but I just can't. From your description, it looks like SayoBot might be blocked on your school computer. I have a couple questions:
Does the home page look like the one in [this issue](https://github.com/WebOsu-2/webosu-2.github.io/issues/12)?
Does the SayoBot website (https://osu.sayobot.cn/home) work, and shows beatmaps?
If you are able to see beatmaps, can you download them? If not, can you explain what happens?
Can you send a screenshot of the console (press F12, then press on the "Console" tab)

And finally, are you able to please send a screenshot (or even better, a recording) of your issue?

If this really is a SayoBot issue, there may be few to no options for me to fix it for you, and you may have to fix it on your side. (especially if SayoBot is a blocked site)

**Comment by Emp1r1c** [comment]
I cant really screen shot it since when I try to open the link it just keeps loading but never finishes (that only goes for the site link and the old webosu sites) and it does look like the other guys issue but when it was still on mino it worked fine for me so it might be sayobot

**Comment by Emp1r1c** [comment]
I am even on a unblocked pc rn and it is still not working but I can see what I can do

**Comment by Emp1r1c** [comment]
I can try and use the URL code for the site by tmr but that's about it on what I can do (even got hella help from the comp tech teacher)

**Comment by Mostlime12195** [comment]
The website itself is not loading? If absolutely nothing loads (not even the website), then that might mean github is blocked on non-functional. The site runs on github.

Please try a proxy https://eu1.proxysite.com/process.php?d=1IqXZNcYNZZuH3MfW2SDamtaGVIVa4s%3D&b=1
(you can switch locations/servers at the top)

unfortunately, the site not loading is not something I have much control over, it is weird that it happens on your unblocked pc. I'll keep asking questions and thinking about this, we might be close to a solution.

**Comment by Emp1r1c** [comment]
that proxy don't works but I know of one that works in my school so I will try that then use the one you said too

**Comment by Emp1r1c** [comment]
it does not work either of the links don't work at all

**Comment by Emp1r1c** [comment]
might be out of luck

**Comment by Mostlime12195** [comment]
can you try switching DNS servers?

**Comment by Emp1r1c** [comment]
I can try but don't count on it

**Comment by Mostlime12195** [comment]
I cannot reproduce this issue, likely an error with the end-user.
